# TODO: Move from Portainer yaml to git
name: homelab-gateway
services:
  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--entryPoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--serverstransport.insecureskipverify=true"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      # - "--accesslog.fields.defaultmode=keep"
      # - "--accesslog.fields.names.ClientUsername=drop"
      # - "--accesslog.fields.headers.defaultmode=keep"
      # - "--accesslog.format=json"
      - "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
      - "--experimental.plugins.htransformation.version=v0.2.7"
    ports:
      - 443:443
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: always

networks:
  default:
    name: homelab-network
    external: true
