name: homelab-gateway
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/whoami"
      - "traefik.http.routers.whoami.middlewares=whoami-stripprefix@docker"

  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN_CHERISH}
    restart: always

networks:
  default:
    name: homelab-network
    external: true

volumes:
  homelab-mysql-volume:
    external: true

secrets:
  mysql-root-password:
    file: ./mysql/secrets/root-password.txt
  mysql-secrets:
    file: ./mysql/secrets/secrets.env
  mysql-nginx-proxy-manager-password:
    file: ./mysql/secrets/nginx-proxy-manager-password.txt
