version: "3.9"
name: homelab-monitoring
networks:
  default:
    name: homelab-network
    external: true

secrets:
  grafana-cloud-token:
    file: ./grafana/secrets/grafana-cloud-token.txt

services:
  grafana:
    image: grafana/agent:latest
    volumes:
      - ./grafana/grafana-agent-flow.river:/etc/agent/config.river
    ports:
      - 12345:12345
    environment:
      - AGENT_MODE=flow
      - GRAFANA_CLOUD_TOKEN_PATH=/run/secrets/grafana-cloud-token
    secrets:
      - grafana-cloud-token
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "/etc/agent/config.river"
