name: homelab-portainer

networks:
  default:
    name: homelab-network
    external: true

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 8000:8000
      - 9443:9443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/portainer`)"
      - "traefik.http.middlewares.traefik-stripprefix.stripprefix.prefixes=/portainer"
      - "traefik.http.routers.traefik.middlewares=traefik-stripprefix@docker"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.scheme=https"
      - "traefik.http.services.traefik.loadbalancer.server.port=9443"
volumes:
  portainer-data:
    external: true
