name: homelab-heimdall

networks:
  default:
    name: homelab-network
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - homelab-heimdall-config:/config
    # ports:
    #   - 80:80
    #   - 443:443
    restart: unless-stopped

volumes:
  homelab-heimdall-config:
    external: true
