name: homelab-keycloak

networks:
  default:
    name: homelab-network
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      # - KC_PROXY=edge
      # Use when configuring Cloudflare Tunnel
      # - KC_HOSTNAME_SCTRICT=false
      - KC_HOSTNAME=localhost
      # Change to default 443 when using Cloudflare Tunnel
      - KC_PORT=8080
    command:
      - "start"
