name: homelab-gateway
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--entryPoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - 443:443
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN_CHERISH}
    restart: always

networks:
  default:
    name: homelab-network
    external: true

volumes:
  homelab-mysql-volume:
    external: true

secrets:
  mysql-root-password:
    file: ./mysql/secrets/root-password.txt
  mysql-secrets:
    file: ./mysql/secrets/secrets.env
  mysql-nginx-proxy-manager-password:
    file: ./mysql/secrets/nginx-proxy-manager-password.txt
