name: homelab-keycloak

networks:
  default:
    name: homelab-network
    external: true

volumes:
  homelab-postgres-data:
    external: true

secrets:
  postgres-db-password:
    file: ./keycloak/secrets/postgres-db-password.txt
  keycloak-db-password:
    file: ./keycloak/secrets/keycloak-db-password.txt

services:
  postgres:
    image: postgres:15
    secrets:
      - postgres-db-password
      - keycloak-db-password
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-db-password
      - KEYCLOAK_DB_NAME=keycloak
      - KEYCLOAK_DB_USER=keycloak
    volumes:
      - homelab-postgres-data:/var/lib/postgresql/data
      - ./keycloak/initdb:/docker-entrypoint-initdb.d
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    depends_on:
      - postgres
    ports:
      - 8443:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_PROXY=reencrypt
      # Use when configuring Cloudflare Tunnel
      # - KC_HOSTNAME_SCTRICT=false
      - KC_HTTPS_CERTIFICATE_FILE=/secrets/certificate.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/secrets/key.pem
      - KC_HOSTNAME=secure.kopparam.com
      - KC_HOSTNAME_SCRICT_BACKCHANNEL=true
      - KC_HOSTNAME_ADMIN=secure.kopparam.com
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./keycloak/secrets:/secrets
    command:
      - "start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`secure.kopparam.com`)"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[0].name=InitForwardedHeader"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[0].type=Set"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[0].value="
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[0].header=Forwarded"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[1].name=SetForwardedHeader"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[1].type=Join"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[1].header=Forwarded"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[1].headerPrefix=^"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[1].sep=,"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[1].values[0]=^Cf-Connecting-Ip"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[2].name=InitXForwardedForHeader"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[2].type=Set"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[2].value="
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[2].header=X-Forwarded-For"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[3].name=SetXForwardedForHeader"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[3].type=Join"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[3].header=X-Forwarded-For"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[3].headerPrefix=^"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[3].sep=,"
      - "traefik.http.middlewares.keycloak-proxy-headers.plugin.htransformation.rules[3].values[0]=^Cf-Connecting-Ip"
      - "traefik.http.routers.keycloak.middlewares=keycloak-proxy-headers@docker"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.scheme=https"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8443"
