version: "3.9"
name: homelab-passbolt
networks:
  default:
    name: homelab-network
    external: true

services:
  passbolt-db:
    container_name: passbolt-db
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${PASSBOLT_DB_NAME:?err}
      - MYSQL_USER=${PASSBOLT_DB_USER:?err}
      - MYSQL_PASSWORD=${PASSBOLT_DB_PASS:?err}
    volumes:
      - passbolt-db:/var/lib/mysql

  passbolt:
    container_name: passbolt-app
    image: passbolt/passbolt:latest-ce
    restart: unless-stopped
    depends_on:
      - passbolt-db
    environment:
      # - APP_FULL_BASE_URL=https://passbolt.kopparam.com
      - APP_BASE=/passbolt
      - DATASOURCES_DEFAULT_HOST=passbolt-db
      - DATASOURCES_DEFAULT_USERNAME=${PASSBOLT_DB_USER:?err}
      - DATASOURCES_DEFAULT_PASSWORD=${PASSBOLT_DB_PASS:?err}
      - DATASOURCES_DEFAULT_DATABASE=${PASSBOLT_DB_NAME:?err}
      - EMAIL_TRANSPORT_DEFAULT_HOST=smtp.mail.me.com
      - EMAIL_TRANSPORT_DEFAULT_PORT=587
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=${EMAIL_TRANSPORT_DEFAULT_USERNAME:?err}
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=${EMAIL_TRANSPORT_DEFAULT_PASSWORD:?err}
      - EMAIL_TRANSPORT_DEFAULT_TLS=true
      - EMAIL_DEFAULT_FROM=${EMAIL_TRANSPORT_DEFAULT_FROM:?err}
    volumes:
      - passbolt-data-gpg:/etc/passbolt/gpg
      - passbolt-data-jwt:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "passbolt-db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.passbolt.rule=Host(`homelab.kopparam.com`) && PathPrefix(`/passbolt`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.scheme=https"
      - "traefik.http.services.keycloak.loadbalancer.server.port=443"
    # ports:
    #   - 80:80
    #   - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  passbolt-db:
  passbolt-data-gpg:
  passbolt-data-jwt:
