services:

  invidious:
    image: quay.io/invidious/invidious:latest-arm64
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      INVIDIOUS_CONFIG_FILE: /config/config.yml
    volumes:
      - /home/k/invidious/config:/config
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.invidious.rule=Host(`invidious.k.it`)"
      - "traefik.http.routers.invidious.entrypoints=internalsecure"
      - "traefik.http.services.invidious.loadbalancer.server.port=3000"

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - invidiouspostgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  invidiouspostgresdata:
    external: true

networks:
  default:
    name: homelab-network
    external: true