services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - paperless-redisdata-nfs:/data
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    volumes:
      - paperless-data-nfs:/usr/src/paperless/data
      - paperless-media-nfs:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - paperless-consume:/usr/src/paperless/consume
      - ./scripts:/usr/src/paperless/scripts
      - /home/k/paperless/passwords.txt:/usr/src/paperless/secrets/passwords.txt
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: "Asia/Singapore"
      PAPERLESS_URL: ${PAPERLESS_URL:?err}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY:?err}
      PAPERLESS_CONSUMER_POLLING: 300
      PAPERLESS_PRE_CONSUME_SCRIPT: /usr/src/paperless/scripts/removepassword.sh
      PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET: ${PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET:?err}
      PAPERLESS_GMAIL_OAUTH_CLIENT_ID: ${PAPERLESS_GMAIL_OAUTH_CLIENT_ID:?err}
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.20
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: paperless
    network_mode: service:paperless
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/serve.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - ./tailscale:/config
    depends_on:
      - paperless

volumes:
  tailscale-state:
  paperless-data-nfs:
    external: true
  paperless-media-nfs:
    external: true
  paperless-redisdata-nfs:
    external: true
  paperless-consume:
    external: true

