---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.5
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/images
      - ./logos:/app/icons
    environment:
      PUID: 1000
      PGID: 100
    restart: unless-stopped

networks:
  default:
    name: homelab-network
    external: true