---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.5
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/images
      - ./logos:/app/icons
    environment:
      PUID: 1000
      PGID: 100
      HOMEPAGE_VAR_PIHOLE_API_TOKEN: ${HOMEPAGE_VAR_PIHOLE_API_TOKEN}
      HOMEPAGE_VAR_PORTAINER_API_TOKEN: ${HOMEPAGE_VAR_PORTAINER_API_TOKEN}
      HOMEPAGE_VAR_ROMM_USERNAME: ${HOMEPAGE_VAR_ROMM_USERNAME}
      HOMEPAGE_VAR_ROMM_PASSWORD: ${HOMEPAGE_VAR_ROMM_PASSWORD}
      HOMEPAGE_VAR_NC_PASSWORD: ${HOMEPAGE_VAR_NC_PASSWORD}
      HOMEPAGE_VAR_NC_USERNAME: ${HOMEPAGE_VAR_NC_USERNAME}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: unless-stopped

networks:
  default:
    name: homelab-network
    external: true