---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/images
      - ./logos:/app/icons
    environment:
      PUID: 1000
      PGID: 100
      HOMEPAGE_VAR_PIHOLE_API_TOKEN: ${HOMEPAGE_VAR_PIHOLE_API_TOKEN}
      HOMEPAGE_VAR_PORTAINER_API_TOKEN: ${HOMEPAGE_VAR_PORTAINER_API_TOKEN}
      HOMEPAGE_VAR_ROMM_USERNAME: ${HOMEPAGE_VAR_ROMM_USERNAME}
      HOMEPAGE_VAR_ROMM_PASSWORD: ${HOMEPAGE_VAR_ROMM_PASSWORD}
      HOMEPAGE_VAR_NC_PASSWORD: ${HOMEPAGE_VAR_NC_PASSWORD}
      HOMEPAGE_VAR_NC_USERNAME: ${HOMEPAGE_VAR_NC_USERNAME}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`ihomepage.kopparam.com`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.routers.homepage.tls.certresolver=kopparamdnsresolver"

networks:
  default:
    name: homelab-network
    external: true