repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana-k8s-monitoring
    namespace: grafana
    chart: grafana/k8s-monitoring
    createNamespace: true
    version: 1.0.12
    values:
      - values.yaml
    secrets:
      - secrets.yaml
