cluster:
  name: kupi
externalServices:
  prometheus:
    host: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net
  loki:
    host: https://logs-prod-020.grafana.net
  tempo:
    host: https://tempo-prod-14-prod-ap-southeast-1.grafana.net:443
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
opencost:
  enabled: false
  opencost:
    exporter:
      defaultClusterId: kupi
    prometheus:
      external:
        url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}
