services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins-network:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    command: --storage-driver overlay2

  jenkins:
    image: myjenkins-blueocean:2.518-jdk21
    container_name: jenkins
    restart: on-failure
    depends_on:
      - jenkins-docker
    networks:
      - jenkins-network
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`ijenkins.kopparam.com`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=kopparamdnsresolver"

networks:
  jenkins-network:
    external: true

volumes:
  jenkins-docker-certs:
  jenkins-data:
