services:
  web:
    environment:
     - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:?err}
    env_file:
      - ./config/prod.env
      - ./config/homelab.env
    volumes:
      - wger-static:/home/wger/static
      - wger-media:/home/wger/media


  nginx:
    volumes:
      - wger-static:/wger/static:ro
      - wger-media:/wger/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.wger.loadbalancer.server.port=8097"
      - "traefik.http.routers.wger.rule=Host(`wger.kopparam.com`)"
      - "traefik.http.routers.wger.entrypoints=websecure"
      - "traefik.http.routers.wger.tls.certresolver=kopparamdnsresolver"

  db:
    volumes:
      - wger-postgres-data:/var/lib/postgresql/data/

  cache:

    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - wger-redis-data:/data


    # You probably want to limit the memory usage of the cache, otherwise it might
    # hog all the available memory. Remove or change according to your needs.
    #mem_limit: 5gb

  celery_worker:
    env_file:
      - ./config/prod.env
      - ./config/homelab.env
    volumes:
      - wger-media:/home/wger/media

  celery_beat:
    volumes:
      - wger-celery-beat:/home/wger/beat/
    env_file:
      - ./config/prod.env
      - ./config/homelab.env

volumes:
  wger-postgres-data:
    external: true
  wger-celery-beat:
    external: true
  wger-redis-data:
    external: true

  # Heads up, if you remove these volumes and use folders directly you need to chown them
  # to the UID and GID 1000 even if it doesn't exist on your system. Also, they should
  # be readable by everyone.
  wger-media:
    external: true
  wger-static:
    external: true

networks:
  default:
    name: homelab-network
    external: true

