repositories:
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts

releases:
  - name: cnpg
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg
    createNamespace: true
    values:
      - cnpg-system.yaml
    wait: true
  - name: cnpg-db-cluster
    namespace: database
    chart: cnpg/cluster
    createNamespace: true
    values:
      - cluster.yaml
    needs:
      - cnpg-system/cnpg
