- name: Initialize Kubernetes cluster
  hosts: rpi5_01
  # ansible_python_interpreter: /home/kashyap/homelab/.venv/bin/python
  become: true
  vars:
    cilium_cli_version: "v0.16.7"
    cilium_version: "1.15.5"
  tasks:
    - name: Check if cilium CLI is already installed
      ansible.builtin.command: cilium version --client
      register: cilium_cli_version_out
    - name: Download cilium CLI
      ansible.builtin.get_url:
        url: 'https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-arm64.tar.gz'
        dest: /tmp/cilium-linux-arm64.tar.gz
        checksum: 'sha256:https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-arm64.tar.gz.sha256sum'
        mode: '0700'
      when: cilium_cli_version not in cilium_cli_version_out.stdout
    - name: Extract cilium CLI
      ansible.builtin.unarchive:
        src: /tmp/cilium-linux-arm64.tar.gz
        dest: /usr/local/bin
        remote_src: true
        mode: '0755'
      when: cilium_cli_version not in cilium_cli_version_out.stdout
    - name: Clean up Cilium CLI
      ansible.builtin.file:
        path: /tmp/cilium-linux-arm64.tar.gz
        state: absent
      when: cilium_cli_version not in cilium_cli_version_out.stdout
    - name: Check if cilium is already installed
      ansible.builtin.command: cilium status
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: cilium_status_out
      ignore_errors: true
    - name: Install Cilium
      ansible.builtin.command: cilium install --version {{ cilium_version }}
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: cilium_install_out
      when: cilium_status_out.rc != 0
    - name: Save output to local
      ansible.builtin.copy:
        content: "{{ cilium_install_out.stdout }}"
        dest: ./cilium_install_out.txt
        owner: k
        group: k
        mode: "0600"
      when: cilium_status_out.rc != 0
