apiVersion: ENC[AES256_GCM,data:a+4=,iv:4UXDj9dPWUAssGVjGeFzd0BIF3vscZkjtLh/hRrLB8w=,tag:8Xqqf4uxeidWYlproTIlHQ==,type:str]
kind: ENC[AES256_GCM,data:sBXpVXU4,iv:5fe7+JeNQr4fcRSCj8b2xrIj5lS1Ak+ne5fu3iMA0Wc=,tag:Fd3sIAKk61OcZiFqG3fPaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LUEoembjO18bTm+boZsiuKTotcB/6/BMB/c=,iv:Lm6/n4oaLHhiG0y0f3clfnRMxpVKidM9lX293m0idak=,tag:3J2VXwCemZQW3aMgJAj6Rw==,type:str]
    namespace: ENC[AES256_GCM,data:fqabfa9x7+Y=,iv:hjObsqJbGjVZbtYIPzHQNz7lwXW8yl+eZOroNZ2ObPM=,tag:mNAHguEmqQHmKuxjcahtYQ==,type:str]
type: ENC[AES256_GCM,data:RiwN6C8g,iv:tRNoxt3o1KgAT+K7xRkDOwXbwb72e65RG5NUnDBCNOE=,tag:DeuuBneLOYxEUEcN6p8/gw==,type:str]
data:
    username: ENC[AES256_GCM,data:xdgZk7Nvbq4NtjQB,iv:MOmpTB107aw3j8SuWdHNvQojAvE2Wo+YuC/YJ9a1sEo=,tag:GO/iWOteEy8uiCAdU8txyQ==,type:str]
    password: ENC[AES256_GCM,data:HwAFynE+WgHkW40Lb0BKSVOExbU=,iv:sHC6/13zd5K1ejgZ0+Irc+PXc1pzlhm0Rajn+++vtjA=,tag:3RXihDfuuzMGI7polOMUTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fsnqmupar6pcfph7vk2f22vp5yn5edwhfgcm9fx54afu8ulxca0skr08zr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRDd2S2twR2MraXRLcmVI
            UmF4RFJmQW1aekhLR09saFdqUFMvQVAwYVZnClhiSHkyWUVCRXRyT1NqVG44QURO
            TlN2NWJXZW52ZHZtcUZtdXpiNFlEdE0KLS0tIEdDeTB0NnhLT3RVNGJKMmJmMXNS
            UTRFdzlmNzltbzgxdXY1L2VFS1I3TUkKwBcpS0CBB1yARsOhfUUgL0jDdv9II4Tu
            EVckF3u8k9RVPa4keNaN88cPWyUwshykWdPMlZo/xXZYqcpCxjj+uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T13:47:19Z"
    mac: ENC[AES256_GCM,data:zenChulFdgLP1qCC4/O81SQuLj6CYxbzpHkXO5zST6TwYhMjZRsDNxxL6CJycUu33oWfQC9t9X6MeLXhE9HlEivRfrxQ3hnFTT0kJzv/caIPVTSdo4EXzzzA0TbQTbkl/oRCV6tPdC070VDDubPidjL09TXp+QvJc52JRXfrKoc=,iv:rIJ1QRdKqgA6CBPeaPFWun8yC1ddHp9FOhENt1x58aI=,tag:EBcmE4fj1XELDnja5eH+nA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
