- name: Create a database and user for Fineract
  hosts: localhost
  tasks:
    - name: Create database
      become: false
      community.postgresql.postgresql_db:
        name: fineract_tenants
        login_host: 127.0.0.1
        login_user: postgres
        login_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
      delegate_to: localhost
    - name: Create user
      community.postgresql.postgresql_user:
        name: fineract
        password: "{{ lookup('env', 'FINERACT_DB_PASSWORD') }}"
        login_host: 127.0.0.1
        login_user: postgres
        login_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    - name: Grant user access to database
      community.postgresql.postgresql_privs:
        database: postgres
        privs: ALL
        type: database
        objs: fineract_tenants
        roles: fineract
        login_host: 127.0.0.1
        login_user: postgres
        login_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    - name: Create fineract namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: fineract
    - name: Create k8s secret with login info
      kubernetes.core.k8s:
        state: present
        src: fineract-db-secret-decrypted.yaml
