- name: Initialize Kubernetes cluster
  hosts: rpi5_01
  become: true
  tasks:
    - name: Enable ipv4 packet forwarding across restarts
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        sysctl_set: true
        reload: true
    - name: Backup cmdline.txt
      ansible.builtin.copy:
        src: /boot/firmware/cmdline.txt
        dest: /boot/firmware/cmdline.txt.bak
        remote_src: true
    - name: Enable cgroups memory
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: true
        regexp: '^(.*)$'
        line: '\1 cgroup_memory=1 cgroup_enable=memory'
        state: present
    - name: Run kubeadm init
      ansible.builtin.command: kubeadm init --control-plane-endpoint=kupi.k.it
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init_out
    - name: Save output to local
      ansible.builtin.copy:
        content: "{{ kubeadm_init_out.stdout }}"
        dest: ./kubeadm_init_out.txt
        owner: k
        group: k
        mode: "0600"
    - name: Copy kubeconfig to user's home directory
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/k/.kube/config
        remote_src: true
        owner: k
        group: k
        mode: "0600"