rpi5s:
  vars:
    ansible_user: k
    ansible_ssh_private_key_file: /home/kashyap/.ssh/rpi_cluster
  hosts:
    rpi5-[01:03].local:
kupi_control_plane_joiners:
  vars:
    ansible_user: k
    ansible_ssh_private_key_file: /home/kashyap/.ssh/rpi_cluster
  hosts:
    rpi5-02.local:
    rpi5-03.local:
ungrouped:
  vars:
    ansible_user: k
    ansible_ssh_private_key_file: /home/kashyap/.ssh/rpi_cluster
  hosts:
    rpi5_01:
      ansible_host: rpi5-01.local
