- name: Add labels to storage nodes
  hosts: localhost
  tasks:
    - name: Add label to storage nodes
      become: false
      environment:
        KUBECONFIG: /home/kashyap/.kube/kupi
      kubernetes.core.k8s:
        state: patched
        kind: Node
        name: "{{ item }}"
        definition:
          metadata:
            labels:
              role: "storage-node"
      loop:
        - rpi5-02
      delegate_to: localhost
