---
- name: Install raspberry pi connect
  hosts: rpi5s
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install rpi-connect&&
      ansible.builtin.apt:
        name: rpi-connect
        state: present
      become: yes
