---
- Infra:
    - Portainer:
        href: https://192.168.18.111:9443
        description: Portainer
        icon: portainer.svg
        widget:
          type: portainer
          url: https://192.168.18.111:9443
          env: 2
          key: {{HOMEPAGE_VAR_PORTAINER_API_TOKEN}}
    - Jenkins:
        href: http://192.168.18.111:8085
        description: CI
        icon: jenkins.svg
    - Traefik:
        href: http://192.168.18.111:8080
        description: Proxy Dashboard
        icon: traefik.svg
        widget:
            type: traefik
            url: http://192.168.18.111:8080
    - Pi-Hole:
        href: http://192.168.18.82:1080/admin
        description: Network wide ad blocking
        icon: pi-hole.svg
        widget:
          type: pihole
          url: http://192.168.18.82:1080
          version: 5
          key: {{HOMEPAGE_VAR_PIHOLE_API_TOKEN}}
- Public:
    - Portfolio:
        href: https://kkoppa.com/
        description: Personal Website
    - Family Tree:
        href: https://family.kopparam.com
        description: D3 tree of my family
    - Home Assistant:
        href: https://ha.kopparam.com
        description: Home automation hub
        icon: home-assistant.svg
    - Next Cloud:
        href: https://nc.kopparam.com
        description: Private Cloud
        icon: nextcloud.svg
        widget:
            type: nextcloud
            url: https://nc.kopparam.com
            username: {{HOMEPAGE_VAR_NC_USERNAME}}
            password: {{HOMEPAGE_VAR_NC_PASSWORD}}
    - Romm:
        href: https://romm.kopparam.com
        description: Retro Games
        icon: romm.svg
        widget:
            type: romm
            url: https://romm.kopparam.com
            username: {{HOMEPAGE_VAR_ROMM_USERNAME}}
            password: {{HOMEPAGE_VAR_ROMM_PASSWORD}}
